/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Characters */
        get: operations["list_characters_api_v1_characters_get"];
        put?: never;
        /** Create Character */
        post: operations["create_character_api_v1_characters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/characters/{character_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Character */
        get: operations["get_character_api_v1_characters__character_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Character */
        patch: operations["update_character_api_v1_characters__character_id__patch"];
        trace?: never;
    };
    "/api/v1/characters/{character_id}/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Avatar */
        post: operations["upload_avatar_api_v1_characters__character_id__avatar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/characters/{character_id}/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Memories */
        get: operations["list_memories_api_v1_characters__character_id__memories_get"];
        put?: never;
        /** Create Memory */
        post: operations["create_memory_api_v1_characters__character_id__memories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/characters/{character_id}/memories/{memory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Memory */
        delete: operations["delete_memory_api_v1_characters__character_id__memories__memory_id__delete"];
        options?: never;
        head?: never;
        /** Update Memory */
        patch: operations["update_memory_api_v1_characters__character_id__memories__memory_id__patch"];
        trace?: never;
    };
    "/api/v1/characters/{character_id}:export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Character */
        get: operations["export_character_api_v1_characters__character_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/characters/{character_id}/sheet-versions:preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Character Sheet */
        post: operations["preview_character_sheet_api_v1_characters__character_id__sheet_versions_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/characters/{character_id}/sheet-versions/{version_id}:activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Character Sheet */
        post: operations["activate_character_sheet_api_v1_characters__character_id__sheet_versions__version_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Campaigns */
        get: operations["list_campaigns_api_v1_campaigns_get"];
        put?: never;
        /** Create Campaign */
        post: operations["create_campaign_api_v1_campaigns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Campaign */
        get: operations["get_campaign_api_v1_campaigns__campaign_id__get"];
        put?: never;
        post?: never;
        /** Delete Campaign */
        delete: operations["delete_campaign_api_v1_campaigns__campaign_id__delete"];
        options?: never;
        head?: never;
        /** Update Campaign */
        patch: operations["update_campaign_api_v1_campaigns__campaign_id__patch"];
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace Memberships */
        put: operations["replace_memberships_api_v1_campaigns__campaign_id__memberships_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Campaign Member */
        post: operations["add_campaign_member_api_v1_campaigns__campaign_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}:activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Campaign */
        post: operations["activate_campaign_api_v1_campaigns__campaign_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}:complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Campaign */
        post: operations["complete_campaign_api_v1_campaigns__campaign_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}:reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reopen Campaign */
        post: operations["reopen_campaign_api_v1_campaigns__campaign_id__reopen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}:archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Campaign */
        post: operations["archive_campaign_api_v1_campaigns__campaign_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}:unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unarchive Campaign */
        post: operations["unarchive_campaign_api_v1_campaigns__campaign_id__unarchive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}:reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Campaign */
        post: operations["reset_campaign_api_v1_campaigns__campaign_id__reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}:export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Campaign */
        get: operations["export_campaign_api_v1_campaigns__campaign_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campaigns/{campaign_id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_v1_campaigns__campaign_id__sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}:end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End Session */
        post: operations["end_session_api_v1_sessions__session_id__end_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_api_v1_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/characters/{character_id}/hp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Hp */
        patch: operations["update_hp_api_v1_sessions__session_id__characters__character_id__hp_patch"];
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages_api_v1_sessions__session_id__messages_get"];
        put?: never;
        /** Send Dm Message */
        post: operations["send_dm_message_api_v1_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/messages:ooc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Correct Message With Ooc */
        post: operations["correct_message_with_ooc_api_v1_sessions__session_id__messages_ooc_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/runtime:stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Runtime */
        post: operations["stop_runtime_api_v1_sessions__session_id__runtime_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/runtime:retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Runtime */
        post: operations["retry_runtime_api_v1_sessions__session_id__runtime_retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session Events */
        get: operations["get_session_events_api_v1_sessions__session_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_preview_character_sheet_api_v1_characters__character_id__sheet_versions_preview_post */
        Body_preview_character_sheet_api_v1_characters__character_id__sheet_versions_preview_post: {
            /** File */
            file: string;
        };
        /** Body_upload_avatar_api_v1_characters__character_id__avatar_post */
        Body_upload_avatar_api_v1_characters__character_id__avatar_post: {
            /** File */
            file: string;
        };
        /** CampaignCreate */
        CampaignCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Characterids */
            characterIds?: string[];
        };
        /** CampaignDetail */
        CampaignDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            lifecycleStatus: components["schemas"]["CampaignLifecycleStatus"];
            /** Archivedat */
            archivedAt: string | null;
            /** Revision */
            revision: number;
            /** Membercount */
            memberCount: number;
            /** Activesessionid */
            activeSessionId: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Members */
            members: components["schemas"]["CampaignMember"][];
            /** Sessions */
            sessions: components["schemas"]["SessionSummary"][];
        };
        /**
         * CampaignLifecycleStatus
         * @enum {string}
         */
        CampaignLifecycleStatus: "PREPARATION" | "ACTIVE" | "COMPLETED";
        /** CampaignMember */
        CampaignMember: {
            /** Characterid */
            characterId: string;
            /** Name */
            name: string;
            /** Maxhp */
            maxHp: number;
            /** Avatarpath */
            avatarPath: string | null;
            /** Isconfigured */
            isConfigured: boolean;
        };
        /** CampaignMemberAdd */
        CampaignMemberAdd: {
            /** Revision */
            revision: number;
            /** Characterid */
            characterId: string;
        };
        /** CampaignMembershipUpdate */
        CampaignMembershipUpdate: {
            /** Revision */
            revision: number;
            /** Characterids */
            characterIds: string[];
        };
        /** CampaignSummary */
        CampaignSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            lifecycleStatus: components["schemas"]["CampaignLifecycleStatus"];
            /** Archivedat */
            archivedAt: string | null;
            /** Revision */
            revision: number;
            /** Membercount */
            memberCount: number;
            /** Activesessionid */
            activeSessionId: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** CampaignUpdate */
        CampaignUpdate: {
            /** Revision */
            revision: number;
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
        };
        /** CharacterCreate */
        CharacterCreate: {
            /** Name */
            name: string;
            /** Roleplayprompt */
            roleplayPrompt: string;
            /** Maxhp */
            maxHp: number;
        };
        /** CharacterDetail */
        CharacterDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Maxhp */
            maxHp: number;
            /** Avatarpath */
            avatarPath: string | null;
            /** Hasroleplayprompt */
            hasRoleplayPrompt: boolean;
            /** Hasactivesheet */
            hasActiveSheet: boolean;
            /** Revision */
            revision: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Roleplayprompt */
            roleplayPrompt: string;
            /** Profilecontent */
            profileContent: string;
            profileStatus: components["schemas"]["ProfileStatus"];
        };
        /** CharacterSheetSnapshot */
        CharacterSheetSnapshot: {
            /**
             * Parserversion
             * @default sad-spirit-v1
             */
            parserVersion: string;
            /** Charactername */
            characterName: string;
            /** Species */
            species: string;
            /** Subspecies */
            subspecies?: string | null;
            /** Classes */
            classes: string[];
            /** Subclasses */
            subclasses: string[];
            /** Background */
            background: string;
            /** Homeland */
            homeland?: string | null;
            /** Languages */
            languages?: string[];
            /** Tools */
            tools?: string[];
            /** Classfeatures */
            classFeatures?: components["schemas"]["NamedDescription"][];
            /** Speciesfeatures */
            speciesFeatures?: components["schemas"]["NamedDescription"][];
            /** Feats */
            feats?: components["schemas"]["NamedDescription"][];
            /** Spells */
            spells?: components["schemas"]["SpellSnapshot"][];
            /** Equipment */
            equipment?: components["schemas"]["NamedDescription"][];
            /** Inventory */
            inventory?: components["schemas"]["NamedDescription"][];
        };
        /** CharacterSummary */
        CharacterSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Maxhp */
            maxHp: number;
            /** Avatarpath */
            avatarPath: string | null;
            /** Hasroleplayprompt */
            hasRoleplayPrompt: boolean;
            /** Hasactivesheet */
            hasActiveSheet: boolean;
            /** Revision */
            revision: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** CharacterUpdate */
        CharacterUpdate: {
            /** Revision */
            revision: number;
            /** Name */
            name?: string | null;
            /** Roleplayprompt */
            roleplayPrompt?: string | null;
            /** Maxhp */
            maxHp?: number | null;
            /** Profilecontent */
            profileContent?: string | null;
        };
        /** DmMessageCommandResult */
        DmMessageCommandResult: {
            message: components["schemas"]["MessageView"];
            runtime: components["schemas"]["RuntimeState"];
        };
        /** DmMessageCreate */
        DmMessageCreate: {
            /** Content */
            content: string;
            /** @default PUBLIC */
            audience: components["schemas"]["MessageAudience"];
            /** Recipientcharacterids */
            recipientCharacterIds?: string[];
            /**
             * Clientrequestid
             * Format: uuid
             */
            clientRequestId: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HpState */
        HpState: {
            /** Characterid */
            characterId: string;
            /** Name */
            name: string;
            /** Currenthp */
            currentHp: number;
            /** Maxhp */
            maxHp: number;
        };
        /** HpUpdate */
        HpUpdate: {
            /** Currenthp */
            currentHp: number;
        };
        /** MemoryCreate */
        MemoryCreate: {
            /** Content */
            content: string;
            /**
             * Pinned
             * @default false
             */
            pinned: boolean;
        };
        /**
         * MemoryOrigin
         * @enum {string}
         */
        MemoryOrigin: "DM" | "AUTO";
        /** MemoryUpdate */
        MemoryUpdate: {
            /** Content */
            content?: string | null;
            /** Pinned */
            pinned?: boolean | null;
        };
        /** MemoryView */
        MemoryView: {
            /** Id */
            id: string;
            /** Characterid */
            characterId: string;
            /** Sourcecampaignid */
            sourceCampaignId: string | null;
            /** Sourcesessionid */
            sourceSessionId: string | null;
            origin: components["schemas"]["MemoryOrigin"];
            /** Content */
            content: string;
            /** Pinned */
            pinned: boolean;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * MessageAudience
         * @enum {string}
         */
        MessageAudience: "PUBLIC" | "PRIVATE" | "DM_ONLY";
        /**
         * MessageKind
         * @enum {string}
         */
        MessageKind: "IN_GAME" | "OOC" | "SYSTEM";
        /** MessageRecipientView */
        MessageRecipientView: {
            /** Characterid */
            characterId: string;
            /** Name */
            name: string;
        };
        /**
         * MessageSenderType
         * @enum {string}
         */
        MessageSenderType: "DM" | "CHARACTER" | "SYSTEM";
        /** MessageView */
        MessageView: {
            /** Id */
            id: string;
            /** Sessionid */
            sessionId: string;
            /** Sequenceno */
            sequenceNo: number;
            senderType: components["schemas"]["MessageSenderType"];
            /** Sendercharacterid */
            senderCharacterId: string | null;
            /** Sendername */
            senderName: string | null;
            kind: components["schemas"]["MessageKind"];
            audience: components["schemas"]["MessageAudience"];
            /** Content */
            content: string;
            /** Isooccorrected */
            isOocCorrected: boolean;
            /** Ooccorrectionnote */
            oocCorrectionNote: string | null;
            /** Recipients */
            recipients: components["schemas"]["MessageRecipientView"][];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** NamedDescription */
        NamedDescription: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** OocCorrectionCreate */
        OocCorrectionCreate: {
            /** Targetmessageid */
            targetMessageId: string;
            /** Correction */
            correction: string;
            /** Replacementcontent */
            replacementContent?: string | null;
            /**
             * Clientrequestid
             * Format: uuid
             */
            clientRequestId: string;
        };
        /**
         * ProfileStatus
         * @enum {string}
         */
        ProfileStatus: "READY" | "NEEDS_REBUILD" | "GENERATING" | "FAILED";
        /** RuntimeState */
        RuntimeState: {
            status: components["schemas"]["RuntimeStatus"];
            /** Generation */
            generation: number;
            /** Activeagentrunid */
            activeAgentRunId: string | null;
            /** Waitingrequest */
            waitingRequest: string | null;
            /** Lasterrorcode */
            lastErrorCode: string | null;
            /** Lasterrormessage */
            lastErrorMessage: string | null;
            /** Consecutiveaimessages */
            consecutiveAiMessages: number;
        };
        /**
         * RuntimeStatus
         * @enum {string}
         */
        RuntimeStatus: "IDLE" | "AGENTS_EVALUATING" | "VALIDATING_MESSAGE" | "WAITING_FOR_DM" | "ERROR" | "ENDED";
        /** SessionCreate */
        SessionCreate: {
            /** Title */
            title: string;
        };
        /** SessionDetail */
        SessionDetail: {
            /** Id */
            id: string;
            /** Campaignid */
            campaignId: string;
            /** Title */
            title: string;
            status: components["schemas"]["SessionStatus"];
            runtimeStatus: components["schemas"]["RuntimeStatus"];
            /** Runtimegeneration */
            runtimeGeneration: number;
            /** Activeagentrunid */
            activeAgentRunId: string | null;
            /** Waitingrequest */
            waitingRequest: string | null;
            /** Lasterrorcode */
            lastErrorCode: string | null;
            /** Lasterrormessage */
            lastErrorMessage: string | null;
            /** Consecutiveaimessages */
            consecutiveAiMessages: number;
            /** Hpstates */
            hpStates: components["schemas"]["HpState"][];
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            /** Endedat */
            endedAt: string | null;
        };
        /**
         * SessionStatus
         * @enum {string}
         */
        SessionStatus: "ACTIVE" | "ENDED";
        /** SessionSummary */
        SessionSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            status: components["schemas"]["SessionStatus"];
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            /** Endedat */
            endedAt: string | null;
        };
        /** SheetActivation */
        SheetActivation: {
            /** Characterid */
            characterId: string;
            /** Activeversionid */
            activeVersionId: string;
            snapshot: components["schemas"]["CharacterSheetSnapshot"];
        };
        /**
         * SheetParseStatus
         * @enum {string}
         */
        SheetParseStatus: "PENDING" | "VALID" | "FAILED";
        /** SheetPreview */
        SheetPreview: {
            /** Versionid */
            versionId: string;
            parseStatus: components["schemas"]["SheetParseStatus"];
            /** Originalfilename */
            originalFilename: string;
            snapshot: components["schemas"]["CharacterSheetSnapshot"];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** SpellSnapshot */
        SpellSnapshot: {
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Category */
            category: string;
            /**
             * School
             * @default
             */
            school: string;
            /**
             * Castingtime
             * @default
             */
            castingTime: string;
            /**
             * Range
             * @default
             */
            range: string;
            /**
             * Duration
             * @default
             */
            duration: string;
            /**
             * Components
             * @default
             */
            components: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_characters_api_v1_characters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterSummary"][];
                };
            };
        };
    };
    create_character_api_v1_characters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_character_api_v1_characters__character_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_character_api_v1_characters__character_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_avatar_api_v1_characters__character_id__avatar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_avatar_api_v1_characters__character_id__avatar_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_memories_api_v1_characters__character_id__memories_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_memory_api_v1_characters__character_id__memories_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_memory_api_v1_characters__character_id__memories__memory_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_memory_api_v1_characters__character_id__memories__memory_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_character_api_v1_characters__character_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_character_sheet_api_v1_characters__character_id__sheet_versions_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_character_sheet_api_v1_characters__character_id__sheet_versions_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SheetPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_character_sheet_api_v1_characters__character_id__sheet_versions__version_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SheetActivation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_campaigns_api_v1_campaigns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignSummary"][];
                };
            };
        };
    };
    create_campaign_api_v1_campaigns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_campaign_api_v1_campaigns__campaign_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_campaign_api_v1_campaigns__campaign_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_campaign_api_v1_campaigns__campaign_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_memberships_api_v1_campaigns__campaign_id__memberships_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignMembershipUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_campaign_member_api_v1_campaigns__campaign_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignMemberAdd"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_campaign_api_v1_campaigns__campaign_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_campaign_api_v1_campaigns__campaign_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reopen_campaign_api_v1_campaigns__campaign_id__reopen_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_campaign_api_v1_campaigns__campaign_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unarchive_campaign_api_v1_campaigns__campaign_id__unarchive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_campaign_api_v1_campaigns__campaign_id__reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_campaign_api_v1_campaigns__campaign_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_v1_campaigns__campaign_id__sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_session_api_v1_sessions__session_id__end_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v1_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_hp_api_v1_sessions__session_id__characters__character_id__hp_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                character_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HpUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_api_v1_sessions__session_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_dm_message_api_v1_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DmMessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DmMessageCommandResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_message_with_ooc_api_v1_sessions__session_id__messages_ooc_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OocCorrectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_runtime_api_v1_sessions__session_id__runtime_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_runtime_api_v1_sessions__session_id__runtime_retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_events_api_v1_sessions__session_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
