"""initial stage one schema

Revision ID: 7bf760e5fb25
Revises:
Create Date: 2026-08-19 21:22:37.040582
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7bf760e5fb25"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaigns",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "lifecycle_status",
            sa.Enum(
                "PREPARATION",
                "ACTIVE",
                "COMPLETED",
                name="campaign_lifecycle_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
    )
    op.create_index(
        "ux_campaign_single_active",
        "campaigns",
        ["lifecycle_status"],
        unique=True,
        sqlite_where=sa.text("lifecycle_status = 'ACTIVE'"),
    )
    op.create_table(
        "characters",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("roleplay_prompt", sa.Text(), nullable=False),
        sa.Column("avatar_path", sa.String(length=500), nullable=True),
        sa.Column("max_hp", sa.Integer(), nullable=False),
        sa.Column("active_sheet_version_id", sa.String(length=36), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("max_hp > 0", name=op.f("ck_characters_positive_max_hp")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_characters")),
    )
    op.create_table(
        "character_profiles",
        sa.Column("character_id", sa.String(length=36), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "READY",
                "NEEDS_REBUILD",
                "GENERATING",
                "FAILED",
                name="profile_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column(
            "updated_by",
            sa.Enum("DM", "SYSTEM", name="updated_by", native_enum=False),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_character_profiles_character_id_characters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("character_id", name=op.f("pk_character_profiles")),
    )
    op.create_table(
        "character_sheet_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("character_id", sa.String(length=36), nullable=False),
        sa.Column("stored_path", sa.String(length=500), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "parse_status",
            sa.Enum("PENDING", "VALID", "FAILED", name="sheet_parse_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("parser_version", sa.String(length=50), nullable=False),
        sa.Column("parsed_snapshot", sa.JSON(), nullable=True),
        sa.Column("parse_error_code", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_character_sheet_versions_character_id_characters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_character_sheet_versions")),
    )
    op.create_index(
        op.f("ix_character_sheet_versions_character_id"),
        "character_sheet_versions",
        ["character_id"],
        unique=False,
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("campaign_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ENDED", name="session_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("next_sequence_no", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "next_sequence_no > 0", name=op.f("ck_sessions_positive_next_sequence_no")
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_sessions_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index(op.f("ix_sessions_campaign_id"), "sessions", ["campaign_id"], unique=False)
    op.create_index(
        "ux_session_single_active_per_campaign",
        "sessions",
        ["campaign_id"],
        unique=True,
        sqlite_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "campaign_memberships",
        sa.Column("campaign_id", sa.String(length=36), nullable=False),
        sa.Column("character_id", sa.String(length=36), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("joined_session_id", sa.String(length=36), nullable=True),
        sa.Column("joined_after_message_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_memberships_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_campaign_memberships_character_id_characters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["joined_session_id"],
            ["sessions.id"],
            name=op.f("fk_campaign_memberships_joined_session_id_sessions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "campaign_id", "character_id", name=op.f("pk_campaign_memberships")
        ),
    )
    op.create_table(
        "session_character_states",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("character_id", sa.String(length=36), nullable=False),
        sa.Column("current_hp", sa.Integer(), nullable=False),
        sa.Column("max_hp_snapshot", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "current_hp <= max_hp_snapshot",
            name=op.f("ck_session_character_states_current_hp_within_max"),
        ),
        sa.CheckConstraint(
            "current_hp >= 0", name=op.f("ck_session_character_states_non_negative_current_hp")
        ),
        sa.CheckConstraint(
            "max_hp_snapshot > 0", name=op.f("ck_session_character_states_positive_max_hp_snapshot")
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
            name=op.f("fk_session_character_states_character_id_characters"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_session_character_states_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "session_id", "character_id", name=op.f("pk_session_character_states")
        ),
    )
    op.create_table(
        "session_runtimes",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "IDLE",
                "AGENTS_EVALUATING",
                "VALIDATING_MESSAGE",
                "WAITING_FOR_DM",
                "ERROR",
                "ENDED",
                name="runtime_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("active_agent_run_id", sa.String(length=36), nullable=True),
        sa.Column("last_trigger_message_id", sa.String(length=36), nullable=True),
        sa.Column("waiting_message_id", sa.String(length=36), nullable=True),
        sa.Column("waiting_request", sa.Text(), nullable=True),
        sa.Column("consecutive_ai_messages", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "consecutive_ai_messages >= 0 AND consecutive_ai_messages <= 12",
            name=op.f("ck_session_runtimes_valid_consecutive_ai_messages"),
        ),
        sa.CheckConstraint(
            "generation >= 0", name=op.f("ck_session_runtimes_non_negative_generation")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_session_runtimes_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_session_runtimes")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("session_runtimes")
    op.drop_table("session_character_states")
    op.drop_table("campaign_memberships")
    op.drop_index(
        "ux_session_single_active_per_campaign",
        table_name="sessions",
        sqlite_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_index(op.f("ix_sessions_campaign_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(
        op.f("ix_character_sheet_versions_character_id"), table_name="character_sheet_versions"
    )
    op.drop_table("character_sheet_versions")
    op.drop_table("character_profiles")
    op.drop_table("characters")
    op.drop_index(
        "ux_campaign_single_active",
        table_name="campaigns",
        sqlite_where=sa.text("lifecycle_status = 'ACTIVE'"),
    )
    op.drop_table("campaigns")
    # ### end Alembic commands ###
